/* GENERATED by packages/tokens — do not edit.
   Source: design/tokens/avo-tokens.json
   Regenerate: pnpm tokens */

export const tokens = {
  "$meta": {
    "product": "AVO Beauty",
    "version": "1.0",
    "currency": {
      "code": "KWD",
      "decimals": 3,
      "digits": "western-always"
    }
  },
  "color": {
    "ink": "#1C1B19",
    "canvas": "#EBE8E1",
    "surface": "#FBFAF8",
    "surfaceAlt": "#F6F4EE",
    "surfaceAlt2": "#F0EEE9",
    "brand": "#6E7F6C",
    "brandDeep": "#5A6B58",
    "brandDeeper": "#4F5E4C",
    "brandTint": "#EEF1EC",
    "brandTint2": "#F6F7F3",
    "hairline": "rgba(28,27,25,0.08)",
    "hairlineInner": "rgba(28,27,25,0.06)",
    "borderControl": "rgba(28,27,25,0.14)",
    "textMuted": "rgba(28,27,25,0.5)",
    "textMutedLabel": "rgba(28,27,25,0.6)",
    "textMutedSoft": "rgba(28,27,25,0.45)",
    "textMutedStrong": "rgba(28,27,25,0.7)",
    "success": "#25D366",
    "positive": "#5E7157",
    "dangerDot": "#B0736F",
    "dangerText": "#8f5a56",
    "dangerBg": "#F6EAE8",
    "warnText": "#8a6d3b",
    "warnBg": "#F3E9CF",
    "toggleOff": "#D9D6CF",
    "disabledBg": "#E7E4DD",
    "whatsappOnGreen": "#0B3D1E",
    "white": "#FFFFFF"
  },
  "brandPresets": {
    "amaraSage": {
      "brand": "#6E7F6C",
      "deep": "#5A6B58",
      "tint": "#EEF1EC",
      "cardFrom": "#78886F",
      "cardTo": "#5E6E59",
      "whiteOnDeep": "4.9:1",
      "whiteOnBrand": "4.27:1"
    },
    "noorRose": {
      "brand": "#B08D8D",
      "deep": "#8A6565",
      "tint": "#F5EDED",
      "cardFrom": "#BC9898",
      "cardTo": "#9C7A7A",
      "whiteOnDeep": "5.1:1",
      "whiteOnBrand": "2.98:1"
    },
    "lilaLilac": {
      "brand": "#8A7CB0",
      "deep": "#6B5C92",
      "tint": "#EFECF5",
      "cardFrom": "#9587BB",
      "cardTo": "#786A9B",
      "whiteOnDeep": "6.0:1",
      "whiteOnBrand": "3.76:1"
    }
  },
  "tier": {
    "bronze": {
      "dot": "#B08D57",
      "pillBg": "#F0EEE9",
      "pillText": "#B08D57"
    },
    "silver": {
      "dot": "#B7BEC4",
      "pillBg": "#ECEEF0",
      "pillText": "#5f6b73"
    },
    "gold": {
      "dot": "#C9A24B",
      "pillBg": "#F3E9CF",
      "pillText": "#8a6d3b"
    },
    "black": {
      "dot": "#3A3A3A",
      "pillBg": "#E3E1DC",
      "pillText": "#3A3A3A"
    },
    "member": {
      "dot": "#6E7F6C",
      "pillBg": "#EEF1EC",
      "pillText": "#5A6B58"
    }
  },
  "plan": {
    "pro": {
      "bg": "#EAE2D6",
      "text": "#8a6d3b"
    },
    "growth": {
      "bg": "#EEF1EC",
      "text": "#5A6B58"
    },
    "starter": {
      "bg": "#F0EEE9",
      "text": "rgba(28,27,25,0.6)"
    }
  },
  "font": {
    "display": "Fraunces, serif",
    "ui": "Inter, system-ui, sans-serif",
    "arabic": "'IBM Plex Sans Arabic', sans-serif"
  },
  "type": {
    "displayXL": {
      "size": 52,
      "weight": 500,
      "lineHeight": 0.9,
      "font": "display"
    },
    "displayL": {
      "size": 30,
      "weight": 500,
      "tracking": "-0.01em",
      "font": "display"
    },
    "displayM": {
      "size": 23,
      "weight": 500,
      "tracking": "-0.01em",
      "font": "display"
    },
    "displayS": {
      "size": 19,
      "weight": 500,
      "font": "display"
    },
    "money": {
      "size": 22,
      "weight": 600,
      "font": "display"
    },
    "bodyL": {
      "size": 15,
      "weight": 400,
      "font": "ui"
    },
    "body": {
      "size": 13.5,
      "weight": 400,
      "font": "ui"
    },
    "bodyS": {
      "size": 12.5,
      "weight": 400,
      "font": "ui"
    },
    "label": {
      "size": 11,
      "weight": 600,
      "tracking": "0.08em",
      "transform": "uppercase",
      "font": "ui"
    }
  },
  "radius": {
    "chip": 10,
    "input": 13,
    "button": 14,
    "card": 16,
    "cardLg": 20,
    "walletCard": 24,
    "sheet": 26,
    "pill": 999
  },
  "space": {
    "cardPadding": 20,
    "gridGap": 16,
    "sectionGap": 24
  },
  "border": {
    "hairline": "1px solid rgba(28,27,25,0.08)",
    "focus": "1.5px solid #6E7F6C"
  },
  "shadow": {
    "segmentedActive": "0 1px 3px rgba(0,0,0,0.08)",
    "toggleKnob": "0 1px 2px rgba(0,0,0,0.2)",
    "walletCard": "0 22px 44px -20px rgba(94,110,89,0.85)"
  },
  "control": {
    "toggleTrack": [
      44,
      26
    ],
    "toggleKnob": 20,
    "minTapTarget": 44
  },
  "motion": {
    "fast": "150ms",
    "sheet": "280ms",
    "zoom": "350ms",
    "easing": "cubic-bezier(.2,.9,.3,1.05)",
    "reducedMotion": "replace all transforms with opacity fades; disable avoscan, avopulse, avosheet"
  },
  "$rules": {
    "brandFill": "White text NEVER sits on `brand`. Any fill carrying white text (primary buttons, badges, active nav) uses `deep`, which must measure >= 4.5:1 against #fff. `brand` is a surface colour: wallet-card gradients, tint backgrounds, progress fills, dots — places where white text either does not appear or appears at display size over a dark gradient stop.",
    "brandOnLight": "Brand-coloured TEXT on a light surface (links, 'Tap to enlarge', active labels) also uses `deep`, not `brand`.",
    "whiteLabelOnboarding": "A merchant supplies one hex. Derive `deep` by reducing lightness until white clears 4.5:1, derive `tint` at ~92% lightness, derive the card gradient as brand +6% / -8% lightness. Reject or auto-correct a hex whose derived deep cannot reach 4.5:1 without shifting more than ~25% lightness — that colour is not viable as a brand token.",
    "minTapTarget": "44px on all mobile surfaces.",
    "money": "Integer fils everywhere. Format to 3 decimals only at the display boundary.",
    "brandFillStatus": "Applied across all six design files. Audited by driving every screen through its states in the live DOM and scanning for white text on opaque backgrounds below 4.5:1 plus brand fills whose only white content is an SVG stroke: zero failures. Three documented exceptions in interaction-spec.md §2 (translucent pills on the wallet card, white checkmarks in stamp dots as non-text graphics, WhatsApp green).",
    "mutedLabel": "Uppercase micro-labels (11px/600) use color.textMutedLabel = rgba(28,27,25,0.6), not 0.45 - 0.45 measures ~3.3:1 and fails at that size. 0.5/0.55 remain the muted body scale. (Token added: the rule mandated 0.6 and the design uses it 154 times, but no 0.6 token existed, so every micro-label would have been hardcoded.)",
    "whatsapp": "WhatsApp green #25D366 is a fixed third-party brand colour: white text on it is 1.98:1. Label WhatsApp buttons with #0B3D1E.",
    "borderControl": "Secondary control borders (bordered buttons, steppers, chips) use color.borderControl = rgba(28,27,25,0.14), used 111 times across the design. color.hairline (0.08) is a row divider and makes a bordered control look unbordered."
  }
} as const;

export type Tokens = typeof tokens;
export type ColorToken = keyof Tokens['color'];
export type BrandPresetName = keyof Tokens['brandPresets'];
export type TypeToken = keyof Tokens['type'];
export type RadiusToken = keyof Tokens['radius'];

export const color = tokens.color;
export const brandPresets = tokens.brandPresets;
export const tier = tokens.tier;
export const plan = tokens.plan;
export const type = tokens.type;
export const radius = tokens.radius;
export const space = tokens.space;
export const motion = tokens.motion;
export const control = tokens.control;

/** design/tokens/avo-tokens.json → $rules.minTapTarget */
export const MIN_TAP_TARGET = tokens.control.minTapTarget;

/** Kuwaiti dinar: 3 decimals, Western digits always. */
export const CURRENCY = tokens.$meta.currency;
