/**
 * Token generator. Run with `pnpm tokens`.
 *
 * design/tokens/avo-tokens.json is the ONLY place a hex may be written. This
 * script fans it out to every surface:
 *
 *   dist/avo-tokens.css   CSS custom properties  → dashboard, owner console
 *   src/generated.ts      typed constants        → everything
 *   dist/native.js        React Native theme     → wallet, scanner
 *
 * CLAUDE.md phase 0: "Design tokens imported from tokens/avo-tokens.json into
 * every surface. Never re-type a hex."
 */

import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const SOURCE = resolve(root, 'design/tokens/avo-tokens.json');

const raw = JSON.parse(readFileSync(SOURCE, 'utf8')) as Record<string, unknown>;

const BANNER = `/* GENERATED by packages/tokens — do not edit.
   Source: design/tokens/avo-tokens.json
   Regenerate: pnpm tokens */`;

// ---------------------------------------------------------------- CSS ------

function cssVarName(group: string, key: string): string {
  const kebab = key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  return `--avo-${group === 'color' ? '' : `${group}-`}${kebab}`.replace('--avo--', '--avo-');
}

function emitCss(): string {
  const lines: string[] = [BANNER, ':root {'];

  const color = raw.color as Record<string, string>;
  // brand / brandDeep / brandTint are emitted in the white-label block below —
  // declaring them twice would leave two sources of truth in one stylesheet.
  const whiteLabelled = new Set(['brand', 'brandDeep', 'brandTint']);
  lines.push('  /* colour */');
  for (const [k, v] of Object.entries(color)) {
    if (whiteLabelled.has(k)) continue;
    lines.push(`  ${cssVarName('color', k)}: ${v};`);
  }

  // The white-label triple. A salon build overrides exactly these three plus the
  // two gradient stops; nothing else in the stylesheet changes.
  const sage = (raw.brandPresets as Record<string, Record<string, string>>).amaraSage!;
  lines.push('');
  lines.push('  /* white-label — a per-salon build overrides only these five */');
  lines.push(`  --avo-brand: ${sage.brand};`);
  lines.push(`  --avo-brand-deep: ${sage.deep};`);
  lines.push(`  --avo-brand-tint: ${sage.tint};`);
  lines.push(`  --avo-card-from: ${sage.cardFrom};`);
  lines.push(`  --avo-card-to: ${sage.cardTo};`);

  const font = raw.font as Record<string, string>;
  lines.push('');
  lines.push('  /* type */');
  for (const [k, v] of Object.entries(font)) lines.push(`  ${cssVarName('font', k)}: ${v};`);

  const type = raw.type as Record<string, Record<string, unknown>>;
  for (const [name, spec] of Object.entries(type)) {
    lines.push(`  ${cssVarName('type', name)}-size: ${spec.size as number}px;`);
    lines.push(`  ${cssVarName('type', name)}-weight: ${spec.weight as number};`);
  }

  for (const group of ['radius', 'space'] as const) {
    const g = raw[group] as Record<string, number>;
    lines.push('');
    lines.push(`  /* ${group} */`);
    for (const [k, v] of Object.entries(g)) lines.push(`  ${cssVarName(group, k)}: ${v}px;`);
  }

  for (const group of ['border', 'shadow', 'motion'] as const) {
    const g = raw[group] as Record<string, string>;
    lines.push('');
    lines.push(`  /* ${group} */`);
    for (const [k, v] of Object.entries(g)) {
      if (k === 'reducedMotion') continue; // prose, not a value
      lines.push(`  ${cssVarName(group, k)}: ${v};`);
    }
  }

  lines.push('}');
  lines.push('');
  lines.push('/* interaction-spec.md §2 — :focus-visible, never :focus. */');
  lines.push(':focus-visible {');
  lines.push('  outline: 2px solid var(--avo-brand-deep);');
  lines.push('  outline-offset: 2px;');
  lines.push('  border-radius: inherit;');
  lines.push('}');
  lines.push('');
  lines.push('/* On the dark owner-console sidebar and scanner frame, #5A6B58 does not');
  lines.push('   carry against #1C1B19. interaction-spec.md §2. */');
  lines.push('.avo-dark :focus-visible { outline-color: #A9BBA6; }');
  lines.push('');
  lines.push('/* interaction-spec.md §3 — reduced motion REMOVES, it does not shorten. */');
  lines.push('@media (prefers-reduced-motion: reduce) {');
  lines.push('  *, *::before, *::after {');
  lines.push('    animation-duration: 0.01ms !important;');
  lines.push('    animation-iteration-count: 1 !important;');
  lines.push('    transition-duration: 0.01ms !important;');
  lines.push('  }');
  lines.push('}');

  return `${lines.join('\n')}\n`;
}

// ------------------------------------------------------------ TypeScript ---

function emitTs(): string {
  return `${BANNER}

export const tokens = ${JSON.stringify(raw, null, 2)} as const;

export type Tokens = typeof tokens;
export type ColorToken = keyof Tokens['color'];
export type BrandPresetName = keyof Tokens['brandPresets'];
export type TypeToken = keyof Tokens['type'];
export type RadiusToken = keyof Tokens['radius'];

export const color = tokens.color;
export const brandPresets = tokens.brandPresets;
export const tier = tokens.tier;
export const plan = tokens.plan;
export const type = tokens.type;
export const radius = tokens.radius;
export const space = tokens.space;
export const motion = tokens.motion;
export const control = tokens.control;

/** design/tokens/avo-tokens.json → \$rules.minTapTarget */
export const MIN_TAP_TARGET = tokens.control.minTapTarget;

/** Kuwaiti dinar: 3 decimals, Western digits always. */
export const CURRENCY = tokens.$meta.currency;
`;
}

// ---------------------------------------------------------- React Native ---

function emitNative(): string {
  const color = raw.color as Record<string, string>;
  const sage = (raw.brandPresets as Record<string, Record<string, string>>).amaraSage!;
  const type = raw.type as Record<string, Record<string, unknown>>;
  const font = raw.font as Record<string, string>;

  const textStyles: Record<string, unknown> = {};
  for (const [name, spec] of Object.entries(type)) {
    const family = font[spec.font as string] ?? font.ui;
    textStyles[name] = {
      fontSize: spec.size,
      fontWeight: String(spec.weight),
      fontFamily: (family ?? '').split(',')[0]?.replace(/['"]/g, '').trim(),
      ...(spec.lineHeight
        ? { lineHeight: Math.round((spec.size as number) * (spec.lineHeight as number)) }
        : {}),
      ...(spec.tracking ? { letterSpacing: trackingToPx(spec.tracking as string, spec.size as number) } : {}),
      ...(spec.transform === 'uppercase' ? { textTransform: 'uppercase' } : {}),
    };
  }

  const theme = {
    color: { ...color, brand: sage.brand, brandDeep: sage.deep, brandTint: sage.tint },
    card: { from: sage.cardFrom, to: sage.cardTo },
    text: textStyles,
    radius: raw.radius,
    space: raw.space,
    control: raw.control,
    tier: raw.tier,
  };

  return `${BANNER}

export const theme = ${JSON.stringify(theme, null, 2)};
export default theme;
`;
}

/** "-0.01em" at 30px → -0.3px. RN letterSpacing is absolute, CSS tracking is relative. */
function trackingToPx(tracking: string, size: number): number {
  const em = Number.parseFloat(tracking);
  return Math.round(em * size * 100) / 100;
}

// ------------------------------------------------------------------ run ----

mkdirSync(resolve(here, '../dist'), { recursive: true });
writeFileSync(resolve(here, '../dist/avo-tokens.css'), emitCss());
writeFileSync(resolve(here, 'generated.ts'), emitTs());
writeFileSync(resolve(here, '../dist/native.js'), emitNative());

console.log('tokens → dist/avo-tokens.css, src/generated.ts, dist/native.js');
