/**
 * Token generator. Run with `pnpm tokens`.
 *
 * design/tokens/avo-tokens.json is the ONLY place a hex may be written. This
 * script fans it out to every surface:
 *
 *   dist/avo-tokens.css   CSS custom properties  → dashboard, owner console
 *   src/generated.ts      typed constants        → everything
 *   dist/native.js        React Native theme     → wallet, scanner
 *
 * CLAUDE.md phase 0: "Design tokens imported from tokens/avo-tokens.json into
 * every surface. Never re-type a hex."
 */

import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const SOURCE = resolve(root, 'design/tokens/avo-tokens.json');

const raw = JSON.parse(readFileSync(SOURCE, 'utf8')) as Record<string, unknown>;

const BANNER = `/* GENERATED by packages/tokens — do not edit.
   Source: design/tokens/avo-tokens.json
   Regenerate: pnpm tokens */`;

// ---------------------------------------------------------------- CSS ------

function cssVarName(group: string, key: string): string {
  const kebab = key.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
  return `--avo-${group === 'color' ? '' : `${group}-`}${kebab}`.replace('--avo--', '--avo-');
}

function emitCss(): string {
  const lines: string[] = [BANNER, ':root {'];

  const color = raw.color as Record<string, string>;
  // brand / brandDeep / brandTint are emitted in the white-label block below —
  // declaring them twice would leave two sources of truth in one stylesheet.
  const whiteLabelled = new Set(['brand', 'brandDeep', 'brandTint']);
  lines.push('  /* colour */');
  for (const [k, v] of Object.entries(color)) {
    if (whiteLabelled.has(k)) continue;
    lines.push(`  ${cssVarName('color', k)}: ${v};`);
  }

  /**
   * The nested colour groups — tier, plan, dark.
   *
   * These reached `generated.ts` and the native theme but never the stylesheet,
   * so a web surface needing a tier pill or a status dot had no custom property
   * to reach for and substituted an approximation. Lane C hit it on the audit
   * log's Rules and Access pills and reported four values rather than inventing
   * them, which is how it was found.
   *
   * Flattened as `--avo-<group>-<key>-<field>` because CSS has no nesting here:
   * `tier.gold.pillBg` becomes `--avo-tier-gold-pill-bg`.
   */
  for (const group of ['tier', 'plan', 'dark'] as const) {
    const entries = raw[group] as Record<string, unknown> | undefined;
    if (!entries) continue;
    lines.push('');
    lines.push(`  /* ${group} */`);
    for (const [key, val] of Object.entries(entries)) {
      if (val && typeof val === 'object') {
        for (const [field, hex] of Object.entries(val as Record<string, string>)) {
          lines.push(`  ${cssVarName(group, `${key}-${field}`)}: ${hex};`);
        }
      } else {
        lines.push(`  ${cssVarName(group, key)}: ${val as string};`);
      }
    }
  }

  // The white-label triple. A salon build overrides exactly these three plus the
  // two gradient stops; nothing else in the stylesheet changes.
  const sage = (raw.brandPresets as Record<string, Record<string, string>>).amaraSage!;
  lines.push('');
  lines.push('  /* white-label — a per-salon build overrides only these five */');
  lines.push(`  --avo-brand: ${sage.brand};`);
  lines.push(`  --avo-brand-deep: ${sage.deep};`);
  lines.push(`  --avo-brand-tint: ${sage.tint};`);
  lines.push(`  --avo-card-from: ${sage.cardFrom};`);
  lines.push(`  --avo-card-to: ${sage.cardTo};`);

  const font = raw.font as Record<string, string>;
  lines.push('');
  lines.push('  /* type */');
  for (const [k, v] of Object.entries(font)) lines.push(`  ${cssVarName('font', k)}: ${v};`);

  const type = raw.type as Record<string, Record<string, unknown>>;
  for (const [name, spec] of Object.entries(type)) {
    lines.push(`  ${cssVarName('type', name)}-size: ${spec.size as number}px;`);
    lines.push(`  ${cssVarName('type', name)}-weight: ${spec.weight as number};`);
  }

  for (const group of ['radius', 'space'] as const) {
    const g = raw[group] as Record<string, number>;
    lines.push('');
    lines.push(`  /* ${group} */`);
    for (const [k, v] of Object.entries(g)) lines.push(`  ${cssVarName(group, k)}: ${v}px;`);
  }

  for (const group of ['border', 'shadow', 'motion'] as const) {
    const g = raw[group] as Record<string, string>;
    lines.push('');
    lines.push(`  /* ${group} */`);
    for (const [k, v] of Object.entries(g)) {
      if (k === 'reducedMotion') continue; // prose, not a value
      lines.push(`  ${cssVarName(group, k)}: ${v};`);
    }
  }

  lines.push('}');
  lines.push('');
  lines.push('/* interaction-spec.md §2 — :focus-visible, never :focus.');
  lines.push('');
  lines.push('   DELIBERATE DEVIATION. The spec writes the ring as a literal');
  lines.push('   `2px solid #6E7F6C` — the Amara `brand` value. Generalising that to');
  lines.push('   `--avo-brand` breaks on a shipped preset. A focus indicator is a');
  lines.push('   non-text graphic, so WCAG 1.4.11 asks 3:1 against the adjacent');
  lines.push('   surface (#FBFAF8). Measured:');
  lines.push('');
  lines.push('     Amara sage   brand 4.10:1 pass    deep 5.47:1 pass');
  lines.push('     Noor rose    brand 2.86:1 FAIL    deep 4.87:1 pass');
  lines.push('     Lila lilac   brand 3.60:1 pass    deep 5.64:1 pass');
  lines.push('');
  lines.push('   So the ring uses `--avo-brand-deep`. On Amara this is a slightly');
  lines.push('   stronger ring than the literal; on Noor rose it is the difference');
  lines.push('   between a visible focus indicator and a failing one. Same class of');
  lines.push('   bug as non-negotiable #9 — a value that holds for the default preset');
  lines.push('   and breaks the white-label promise. Asserted in derive.test.ts. */');
  lines.push(':focus-visible {');
  lines.push('  outline: 2px solid var(--avo-brand-deep);');
  lines.push('  outline-offset: 2px;');
  lines.push('  border-radius: inherit;');
  lines.push('}');
  lines.push('');
  lines.push('/* On the dark owner-console sidebar and scanner frame, #5A6B58 does not');
  lines.push('   carry against #1C1B19. interaction-spec.md §2. */');
  lines.push('.avo-dark :focus-visible { outline-color: #A9BBA6; }');
  lines.push('');
  lines.push('/* interaction-spec.md §3 — reduced motion REMOVES, it does not shorten. */');
  lines.push('@media (prefers-reduced-motion: reduce) {');
  lines.push('  *, *::before, *::after {');
  lines.push('    animation-duration: 0.01ms !important;');
  lines.push('    animation-iteration-count: 1 !important;');
  lines.push('    transition-duration: 0.01ms !important;');
  lines.push('  }');
  lines.push('}');

  return `${lines.join('\n')}\n`;
}

// ------------------------------------------------------------ TypeScript ---

function emitTs(): string {
  return `${BANNER}

export const tokens = ${JSON.stringify(raw, null, 2)} as const;

export type Tokens = typeof tokens;
export type ColorToken = keyof Tokens['color'];
export type BrandPresetName = keyof Tokens['brandPresets'];
export type TypeToken = keyof Tokens['type'];
export type RadiusToken = keyof Tokens['radius'];

export const color = tokens.color;
export const brandPresets = tokens.brandPresets;
export const tier = tokens.tier;
export const plan = tokens.plan;
export const type = tokens.type;
export const radius = tokens.radius;
export const space = tokens.space;
export const motion = tokens.motion;
export const control = tokens.control;

/** design/tokens/avo-tokens.json → \$rules.minTapTarget */
export const MIN_TAP_TARGET = tokens.control.minTapTarget;

/** Kuwaiti dinar: 3 decimals, Western digits always. */
export const CURRENCY = tokens.$meta.currency;
`;
}

// ---------------------------------------------------------- React Native ---

/**
 * The native theme as an object. Built once and serialised twice — as JS and as
 * a declaration — so the two cannot drift. Re-parsing the emitted JS to derive
 * the types would make the declaration a function of a string, which is how a
 * generator ends up lying about itself.
 */
function nativeTheme(): Record<string, unknown> {
  const color = raw.color as Record<string, string>;
  const sage = (raw.brandPresets as Record<string, Record<string, string>>).amaraSage!;
  const type = raw.type as Record<string, Record<string, unknown>>;
  const font = raw.font as Record<string, string>;

  const textStyles: Record<string, unknown> = {};
  for (const [name, spec] of Object.entries(type)) {
    const family = font[spec.font as string] ?? font.ui;
    textStyles[name] = {
      fontSize: spec.size,
      fontWeight: String(spec.weight),
      fontFamily: (family ?? '').split(',')[0]?.replace(/['"]/g, '').trim(),
      ...(spec.lineHeight
        ? { lineHeight: Math.round((spec.size as number) * (spec.lineHeight as number)) }
        : {}),
      ...(spec.tracking ? { letterSpacing: trackingToPx(spec.tracking as string, spec.size as number) } : {}),
      ...(spec.transform === 'uppercase' ? { textTransform: 'uppercase' } : {}),
    };
  }

  return {
    color: { ...color, brand: sage.brand, brandDeep: sage.deep, brandTint: sage.tint },
    card: { from: sage.cardFrom, to: sage.cardTo },
    // The scanner frame and owner-console sidebar are dark by design, not by
    // theme. dark.focusRing is mandatory there — interaction-spec.md §2.
    dark: raw.dark,
    text: textStyles,
    radius: raw.radius,
    space: raw.space,
    control: raw.control,
    tier: raw.tier,
  };
}

function emitNative(): string {
  const theme = nativeTheme();
  return `${BANNER}

export const theme = ${JSON.stringify(theme, null, 2)};
export default theme;
`;
}

/** "-0.01em" at 30px → -0.3px. RN letterSpacing is absolute, CSS tracking is relative. */
function trackingToPx(tracking: string, size: number): number {
  const em = Number.parseFloat(tracking);
  return Math.round(em * size * 100) / 100;
}

// ------------------------------------------------------------------ run ----

/**
 * A declaration file for the native theme.
 *
 * Without it, `@avo/tokens/native` is untyped and every consumer hand-copies a
 * declaration — which both mobile apps did, and which is the exact drift this
 * generator exists to prevent. A generated artifact that forces a hand-written
 * companion is not generated.
 *
 * Emitted as a structural type of the real object rather than a hand-maintained
 * interface, so it cannot fall behind the values it describes.
 */
function emitNativeTypes(): string {
  const shape = (v: unknown, indent = 2): string => {
    if (Array.isArray(v)) return `readonly ${shape(v[0], indent)}[]`;
    if (v && typeof v === 'object') {
      const pad = ' '.repeat(indent);
      const rows = Object.entries(v as Record<string, unknown>)
        .map(([k, val]) => `${pad}readonly ${JSON.stringify(k)}: ${shape(val, indent + 2)};`)
        .join('\n');
      return `{\n${rows}\n${' '.repeat(indent - 2)}}`;
    }
    return typeof v === 'number' ? 'number' : typeof v === 'boolean' ? 'boolean' : 'string';
  };

  const theme = nativeTheme();
  const { text, ...rest } = theme as { text: Record<string, unknown> };

  /**
   * ONE interface for every text token, not nine literal shapes.
   *
   * Both mobile apps have a `text(token)` helper. If each token gets its own
   * literal type, `theme.text[token]` is a union of nine, and the fields that
   * only some tokens carry — lineHeight, letterSpacing, textTransform — become
   * unreadable from it. The first version of this generator did exactly that
   * and pushed the workaround into every native consumer, which is the same
   * class of problem the missing .d.ts was.
   *
   * Optional where a token may omit it, and `textTransform` is the literal
   * rather than `string`, so React Native's own prop type accepts it without
   * the consumer narrowing first.
   */
  const tokenNames = Object.keys(text)
    .map((k) => JSON.stringify(k))
    .join(' | ');

  return `${BANNER}

export interface NativeTextStyle {
  readonly fontSize: number;
  readonly fontWeight: string;
  readonly fontFamily: string;
  readonly lineHeight?: number;
  readonly letterSpacing?: number;
  readonly textTransform?: 'uppercase';
}

export type TextToken = ${tokenNames};

declare const theme: ${shape(rest).replace(/\n}$/, '')}
  readonly text: Readonly<Record<TextToken, NativeTextStyle>>;
};

export { theme };
export default theme;
`;
}

mkdirSync(resolve(here, '../dist'), { recursive: true });
writeFileSync(resolve(here, '../dist/avo-tokens.css'), emitCss());
writeFileSync(resolve(here, 'generated.ts'), emitTs());
writeFileSync(resolve(here, '../dist/native.js'), emitNative());
writeFileSync(resolve(here, '../dist/native.d.ts'), emitNativeTypes());

console.log('tokens → dist/avo-tokens.css, src/generated.ts, dist/native.js, dist/native.d.ts');
