import {
  useMutation,
  useQuery,
  useQueryClient,
  type UseMutationResult,
  type UseQueryResult,
} from '@tanstack/react-query';
import { parseFils, parseKwdInput, type Fils } from '@avo/types';
import { authedRequest } from '../auth/authedRequest.js';

/**
 * AVO-issued vouchers — the console's three endpoints, in `api/src/routes/vouchers.ts`.
 *
 *   POST   /v1/vouchers              issue one against a member
 *   GET    /v1/vouchers?memberId=    her list
 *   DELETE /v1/vouchers/:id          void an unredeemed one
 *
 * The fourth, `POST /members/me/vouchers/redeem`, is the CUSTOMER's and belongs
 * to the wallet. Nothing in this file can reach it and nothing here should try:
 * the console issues the instrument, she decides when to spend it.
 *
 * =========================================================================
 * THE GATE IS `accounts`, NOT A SECTION OF ITS OWN
 * =========================================================================
 * All three are `requirePlatform(req, 'accounts')` — the SAME argument the route
 * file makes for itself: "a voucher is a compensation instrument, and `accounts`
 * is the console section where a customer's wallet is already adjusted. A
 * merchant cannot reach this at all, which is the authority decision Aftab made."
 *
 * So this is console-only. `authedRequest('owner', …)` on every call, and there
 * is no merchant hook in this file to be imported by accident.
 *
 * Driven as the analyst `mariam.k` (`activity: true, accounts: false`) against a
 * real API on `avo_lane_c`. All three refuse INDEPENDENTLY — the write is not
 * gated by the read having refused first, which is non-negotiable #7's actual
 * claim rather than the UI's:
 *
 *   GET    /v1/vouchers          -> 403 "Your console account cannot open
 *                                        Accounts. The platform owner can grant it."
 *   POST   /v1/vouchers          -> 403  (the same sentence)
 *   DELETE /v1/vouchers/VCH-nope -> 403  (the same sentence, and BEFORE the 404
 *                                        that a missing id would otherwise get —
 *                                        so the gate does not leak which ids exist)
 *
 * It is the same sentence the Accounts LIST is refused with, because it is the
 * same section. `SectionError` renders it verbatim.
 *
 * =========================================================================
 * NO IDEMPOTENCY KEY ON THE ISSUE, AND THAT IS NOT AN OVERSIGHT OF #4
 * =========================================================================
 * The route says it: "Non-negotiable #4 covers money-moving POSTs, and issuing
 * moves NONE — it writes a row. The money moves when she redeems, and that
 * endpoint takes a key."
 *
 * `RequestOptions.idempotencyKey` exists on this client and is deliberately not
 * passed. A double-clicked Issue button therefore produces TWO vouchers rather
 * than one, which is the honest outcome: two rows an admin can see and void, not
 * a silent second credit. The button is disabled while the mutation is in flight,
 * which is a courtesy over that — not a control.
 *
 * =========================================================================
 * NO `code` FIELD, REFUSED BY NAME BY THE SERVER
 * =========================================================================
 * `POST /v1/vouchers` answers 400 `code_not_client_supplied` — "A voucher code is
 * generated by the server, not sent by the console" — because "a console that
 * chose the code could choose a guessable one". So `IssueVoucherInput` has no
 * field to put one in, the same way `SendResetInput` has no password field. The
 * form cannot send what the type cannot hold.
 */

/* ------------------------------------------------------------------ the row -- */

export interface Voucher {
  id: string;
  /** The server-minted code she types into the wallet. Crockford-ish, 12 chars. */
  code: string;
  memberId: string;
  /** NON-NEGOTIABLE #1. Integer fils on the wire, branded at this boundary. */
  amountFils: Fils;
  reason: string;
  /** ISO instant, or null for a voucher that does not expire. */
  expiresAt: string | null;
  createdAt: string;
  redeemedAt: string | null;
  /**
   * The `transaction` row the credit landed on. PARSED AND NOT DRAWN — see
   * `AccountVouchers.tsx` § what is not drawn. It is read here because the
   * record should arrive whole rather than with a hole where a field was.
   */
  redeemedTransactionId: string | null;
  voidedAt: string | null;
  /**
   * DERIVED SERVER-SIDE FROM THE SAME THREE TIMESTAMPS the redeem endpoint uses,
   * "so the console does not reimplement the predicate and cannot disagree with
   * the redeem endpoint about whether a row is live".
   *
   * WHICH MEANS THIS CLIENT MUST NOT RECOMPUTE IT. The obvious client-side
   * version — `expiresAt > Date.now()` — is evaluated against the BROWSER's
   * clock, and a laptop an hour fast would draw a live voucher as expired and
   * withhold the Void button from the one row that still needs it. The screen
   * reads this field for liveness and the timestamps only to NAME which of the
   * three dead states a row is in.
   */
  redeemable: boolean;
}

export interface VoucherList {
  items: Voucher[];
  /**
   * The endpoint's `LIMIT 200`, reported rather than hidden — "a cap, said out
   * loud rather than a `nextCursor: null` that lies". Rendered, for the reason
   * `stateCensus.test.ts` § "a capped list does not report itself as complete"
   * gives: honest on the wire is worth nothing if the client drops it.
   */
  truncated: boolean;
}

/*
 * `nextCursor` IS NOT PARSED, AND THE OMISSION IS THE DECISION — `ShopOrders`'s
 * ruling, which the census pins there. The endpoint sends it always-null beside
 * the honest `truncated`; a client that grew a "load more" off it would page
 * forever on a cursor that never advances. There is nothing to carry, so nothing
 * is read.
 */

/* --------------------------------------------------------------- the parser -- */

function str(v: unknown, where: string): string {
  if (typeof v !== 'string') throw new Error(`${where} was not a string.`);
  return v;
}

function nullableStr(v: unknown, where: string): string | null {
  return v === null || v === undefined ? null : str(v, where);
}

function bool(v: unknown, where: string): boolean {
  if (typeof v !== 'boolean') throw new Error(`${where} was not a boolean.`);
  return v;
}

/**
 * PARSED FIELD BY FIELD AGAINST A REAL RESPONSE, not against the interface.
 *
 * The payload below is a live 201 from `POST /v1/vouchers` on `avo_lane_c`,
 * transcribed here so the next reader can check the parser against the wire
 * rather than against this file's own opinion of it:
 *
 *   {"id":"VCH-be12025e-e1c","code":"LPGMQZF92S43","memberId":"8842",
 *    "amountFils":5000,"reason":"Late appointment, 12 Sep","expiresAt":null,
 *    "createdAt":"2026-09-15T08:47:14.188Z","redeemedAt":null,
 *    "redeemedTransactionId":null,"voidedAt":null,"redeemable":true}
 *
 * `parseFils` and not a cast: `amountFils` is what the whole feature is about,
 * and a string or a float arriving there should fail here rather than reach a
 * `formatFils` that would render it as something plausible.
 */
export function parseVoucher(raw: unknown, where: string): Voucher {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    throw new Error(`${where} was not an object.`);
  }
  const v = raw as Record<string, unknown>;
  return {
    id: str(v.id, `${where}.id`),
    code: str(v.code, `${where}.code`),
    memberId: str(v.memberId, `${where}.memberId`),
    amountFils: parseFils(v.amountFils),
    reason: str(v.reason, `${where}.reason`),
    expiresAt: nullableStr(v.expiresAt, `${where}.expiresAt`),
    createdAt: str(v.createdAt, `${where}.createdAt`),
    redeemedAt: nullableStr(v.redeemedAt, `${where}.redeemedAt`),
    redeemedTransactionId: nullableStr(v.redeemedTransactionId, `${where}.redeemedTransactionId`),
    voidedAt: nullableStr(v.voidedAt, `${where}.voidedAt`),
    redeemable: bool(v.redeemable, `${where}.redeemable`),
  };
}

export function parseVoucherList(raw: unknown): VoucherList {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    throw new Error('GET /v1/vouchers did not answer an object.');
  }
  const r = raw as Record<string, unknown>;
  if (!Array.isArray(r.items)) throw new Error('vouchers.items was not an array.');
  return {
    items: r.items.map((row, i) => parseVoucher(row, `vouchers.items[${i}]`)),
    truncated: bool(r.truncated, 'vouchers.truncated'),
  };
}

/* ----------------------------------------------------------- the dead states -- */

/**
 * WHICH of the four states a row is in, named rather than inferred twice.
 *
 * `redeemable` is the server's answer and the ONLY source for "is this live" —
 * see the field's docstring. The timestamps are consulted solely to say WHY a
 * dead row is dead, and the precedence is the API's own: the schema constraint
 * `voucher_is_not_both_redeemed_and_voided` makes redeemed and void mutually
 * exclusive, and expiry is what is left when neither timestamp is set.
 *
 * A fifth answer is impossible by construction and there is no fallback arm,
 * deliberately: if `redeemable` is false with all three timestamps null, that is
 * a server that grew a fourth reason, and it should surface as a wrong label
 * somebody reports rather than as a silent "Expired".
 */
export type VoucherState = 'redeemable' | 'redeemed' | 'void' | 'expired';

export function voucherState(v: Voucher): VoucherState {
  if (v.redeemedAt !== null) return 'redeemed';
  if (v.voidedAt !== null) return 'void';
  return v.redeemable ? 'redeemable' : 'expired';
}

/* ---------------------------------------------------------------- the amount -- */

/**
 * NON-NEGOTIABLE #1, AT THE ONE PLACE OPERATOR TEXT BECOMES MONEY.
 *
 * `api/products.ts § readPriceInput` is the shape and the argument is identical:
 * `parseKwdInput` from `@avo/types`, never a local `Number(x) * 1000`, because
 * `5.5 * 1000` is a float multiplication and this is money. Three answers rather
 * than two — empty is a person who selected the field and started again, not an
 * error to shout about.
 *
 * NOT A CALL TO `readPriceInput` ITSELF, and that is a choice rather than a
 * duplication: its refusals say "price", and its zero rule cites
 * `product_price_positive`. A voucher amount is neither a price nor bound by that
 * constraint. The server's rule here is `invalid_amount` — "amountFils must be a
 * positive whole number of fils. A voucher only adds." — and the sentence below
 * is that rule in the console's own words, pre-empting a 400 round trip.
 */
export type AmountInput =
  | { kind: 'empty' }
  | { kind: 'invalid'; message: string }
  | { kind: 'ok'; amountFils: Fils };

export function readAmountInput(raw: string): AmountInput {
  const trimmed = raw.trim();
  if (trimmed === '') return { kind: 'empty' };

  let parsed: Fils;
  try {
    parsed = parseKwdInput(trimmed);
  } catch {
    return {
      kind: 'invalid',
      message: `“${trimmed}” isn’t an amount. Use up to 3 decimals, like 5.250.`,
    };
  }

  /*
   * `<= 0` and not `< 0`. The server refuses both with one sentence, and a
   * zero-value voucher is the worse of the two: it would sit in her wallet
   * looking like an apology and credit nothing when she spent it.
   */
  if (parsed <= 0) {
    return { kind: 'invalid', message: 'A voucher has to be worth more than zero.' };
  }
  return { kind: 'ok', amountFils: parsed };
}

/** The API's own cap on `reason`, so the field can stop rather than collect a 400. */
export const REASON_MAX = 300;

/* ----------------------------------------------------------------- the read -- */

export const voucherKeys = {
  all: ['vouchers'] as const,
  forMember: (memberId: string) => ['vouchers', memberId] as const,
};

/**
 * One customer's vouchers, newest first.
 *
 * `?memberId=` IS ALWAYS SENT. The endpoint serves the unfiltered platform-wide
 * list when it is omitted, and this client never asks for it — `serialiseVoucher`
 * carries `memberId` and no member NAME, so an unfiltered list would render as a
 * column of opaque ids. `AccountVouchers.tsx § what is not drawn` has the whole
 * argument and the endpoint it is waiting on.
 */
export function useMemberVouchers(memberId: string): UseQueryResult<VoucherList> {
  return useQuery({
    queryKey: voucherKeys.forMember(memberId),
    queryFn: async ({ signal }) => {
      const raw = await authedRequest<unknown>(
        'owner',
        `/v1/vouchers?memberId=${encodeURIComponent(memberId)}`,
        { signal },
      );
      return parseVoucherList(raw);
    },
  });
}

/* ---------------------------------------------------------------- the writes -- */

export interface IssueVoucherInput {
  memberId: string;
  amountFils: Fils;
  reason: string;
  /** ISO instant, or omitted. The server refuses one in the past by name. */
  expiresAt?: string;
}

/**
 * `POST /v1/vouchers`, 201.
 *
 * INVALIDATES HER LIST, unlike `useSendResetLink` which deliberately invalidates
 * nothing. The difference is real rather than a habit: a reset link changes no
 * field the accounts list serves, and issuing a voucher adds a ROW to exactly the
 * list rendered underneath the form. Not refetching would leave an admin looking
 * at a list that does not contain the thing she just created, and she would issue
 * it again.
 *
 * Scoped to the one member's key, not `voucherKeys.all` — nothing else in the
 * console holds a voucher list to go stale.
 */
export function useIssueVoucher(): UseMutationResult<Voucher, unknown, IssueVoucherInput> {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (input: IssueVoucherInput) => {
      const raw = await authedRequest<unknown>('owner', '/v1/vouchers', {
        method: 'POST',
        /*
         * `amountFils` crosses as the branded integer it already is. No
         * arithmetic happens here and none should: the conversion from typed KWD
         * happened once, in `readAmountInput`, and a second touch is a second
         * place for a float to appear.
         */
        body: {
          memberId: input.memberId,
          amountFils: input.amountFils,
          reason: input.reason,
          ...(input.expiresAt === undefined ? {} : { expiresAt: input.expiresAt }),
        },
      });
      if (typeof raw !== 'object' || raw === null) {
        throw new Error('POST /v1/vouchers did not answer an object.');
      }
      return parseVoucher((raw as Record<string, unknown>).voucher, 'issue.voucher');
    },
    onSuccess: (v) => {
      void qc.invalidateQueries({ queryKey: voucherKeys.forMember(v.memberId) });
    },
  });
}

export interface VoidVoucherInput {
  id: string;
  /** Not sent — the key to invalidate once the server has answered. */
  memberId: string;
}

/**
 * `DELETE /v1/vouchers/:id`, 200.
 *
 * THE SERVER IS THE ARBITER AND THE SCREEN IS NOT. The handler's WHERE clause
 * carries the transition (`isNull(voidedAt)` AND `isNull(redeemedAt)`) and the
 * row count decides, "so two admins clicking Void produce one void and one
 * refusal". Withholding the button on a non-live row is the courtesy over that;
 * these are the two refusals it is a courtesy over, both driven:
 *
 *   already void -> 409 voucher_not_voidable
 *                   "That voucher is already void."
 *   redeemed     -> 409 voucher_not_voidable
 *                   "That voucher has been redeemed. Its credit is in the
 *                    customer’s wallet and cannot be taken back here."
 *
 * The second is non-negotiable #5 answering in the server's own voice, and it is
 * why `WriteError` renders a 409 verbatim rather than paraphrasing: "cannot be
 * taken back here" is the sentence that stops an admin looking for a cash path.
 */
export function useVoidVoucher(): UseMutationResult<Voucher, unknown, VoidVoucherInput> {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id }: VoidVoucherInput) => {
      const raw = await authedRequest<unknown>('owner', `/v1/vouchers/${encodeURIComponent(id)}`, {
        method: 'DELETE',
      });
      if (typeof raw !== 'object' || raw === null) {
        throw new Error('DELETE /v1/vouchers/{id} did not answer an object.');
      }
      return parseVoucher((raw as Record<string, unknown>).voucher, 'void.voucher');
    },
    onSuccess: (_v, input) => {
      void qc.invalidateQueries({ queryKey: voucherKeys.forMember(input.memberId) });
    },
  });
}
